/* Requires the Docker Pipeline plugin */
pipeline {
    agent any
    stages {
        stage('Environment Info') {
            steps {
                sh '''
                echo $PATH
                pwd
                which python3
                cp /var/jenkins_home/data/kaggle.json /var/jenkins_home/workspace/test/lab5/
                '''
            }
        }
        stage('Copy Credentials') {
            steps {
                sh 'cp /var/jenkins_home/data/kaggle.json /var/jenkins_home/workspace/test/lab5/'
            }
        }
        stage('Create Dataset') {
            steps {
                sh 'jupyter nbconvert --execute lab5/lab5.ipynb --to python'
            }
        }
        stage('Test Dataset') {
            steps {
                sh '''
                pwd
                pytest lab5/test_datasets.py
                '''
            }
        }
    }
    post('Always run') {
        always {
            sh 'echo Pipeline has completed!'
        }
    }
}