/* Requires the Docker Pipeline plugin */
pipeline {
    agent any
    stages {
        stage('build') {
            steps {
		sh '''
		pwd
		whoami
		echo $SHELL
		lab2/test.sh
        python3 -V
        pip3 -V
		python3 lab2/test.py
        . /opt/env/bin/activate
        chmod -R 777 /opt/env/lib/python3.11/site-packages
        pip3 install -r requirements.txt
		'''
            }
        }
        stage('test') {
            steps {
                sh 'echo test'
            }
        }
    }
}
