/* Requires the Docker Pipeline plugin */
pipeline {
    agent any
    stages {
        stage('build') {
            steps {
		sh '''
		pwd
		whoami
		echo $SHELL
		lab2/test.sh
		apt-get install python3
		'''
            }
        }
        stage('test') {
            steps {
                sh 'echo test'
            }
        }
    }
}
