/* Requires the Docker Pipeline plugin */
pipeline {
    agent any
    stages {
        stage('build') {
            steps {
		sh '''
		pwd
		apt update
		'''
            }
        }
        stage('test') {
            steps {
                sh 'echo test'
            }
        }
    }
}
